// Server actions auth
export * from "./auth/register-action";
// Server actions bookings
export * from "./booking/create-booking";
export * from "./booking/get-booking";
// Server actions  dashboard
export * from "./dashboard/dashboard-data";
// Server actions onboarding
export * from "./onboarding/onboarding-action";
// Server actions services
export * from "./services/add-services";
export * from "./services/delete-service";
export * from "./services/get-services";
export * from "./services/update-services";
//  Server actions customers
export * from "./customer/get-customers-list";
export * from "./customer/search-customer-by-name";
export * from "./customer/send-discount-action";

export * from './inputs/create-inputs-action'
export * from './inputs/get-inputs-list-action'
